### ISSUE TITLE
iClipの判定でlipSync.aClipを比較している

### ISSUE THREAD

**Issue by Taoqinglong** [hecomi/MMD4Mecanim-LipSync-Plugin#11]
https://github.com/hecomi/MMD4Mecanim-LipSync-Plugin/blob/ab7961004daa424802b95629a32880d2dca996ad/Assets/LipSync/Editor/LipSyncCoreEditor.cs#L228

**Comment by hecomi** [comment]
ご報告ありがとうございました！
