### ISSUE TITLE
MMD4Mecanim The unitypackage has not been uploaded, and there is no instance scenario or model in the project. I don't know how to drive it

### ISSUE THREAD

**Issue by LikeScientist** [hecomi/MMD4Mecanim-LipSync-Plugin#12]

**Comment by hecomi** [comment]
Please get the unitypackage from
- https://stereoarts.jp/

You can also get documentation about how to use it in this page (written in Japanese, so please use google translate or something).

Or I recommend using uLipSync instead if you want to apply a lipsync to your model
- https://github.com/hecomi/uLipSync
